resolver:
  name: default-snapshot
  location: snapshot.yaml

compiler: ghcjs-0.2.1.9008015_ghc-8.0.2
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008015_ghc-8.0.2:
           url: ghc-8.0-2017-05-30-lts-8.15-9008015-mem.tar.gz

ghc-options:
  "*": -dedupe -O0
