resolver:
  name: default-snapshot
  location: snapshot.yaml

compiler: ghcjs-0.2.1.9008013_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008013_ghc-8.0.1:
        url: /home/db/Downloads/ghcjs/ghcjs-0.2.1.9008013_ghc-8.0.1.tar.gz

ghc-options:
  "*": -dedupe -O0
